FROM node:14.15.5

LABEL version="1.0"
LABEL maintainer = ["tienlm@infoplusvn.com"]

WORKDIR /home/app

COPY ["package.json","package-lock.json","./"]

RUN yarn install 

COPY . .

RUN yarn build

EXPOSE 5000

CMD ["node" , "dist/app.js"]


